### ISSUE TITLE
Delete all that "tree" stuff

### ISSUE THREAD

**Issue by ralphbean** [fedora-modularity/product-definition-center#12]
Cut down that :evergreen_tree:.

In product-definition-center/product-definition-center#431, there is a bunch of stuff about "trees" that we're not using and we don't need.  We should remove it all to make that review more simple.

**Comment by mprahl** [comment]
As part of this, we'll need to update the documentation because the docs weren't updated as the models changed (e.g. required fields such as modulemd aren't shown).

**Comment by ralphbean** [comment]
This is handled by #16.
